#!/bin/bash
if [[ $# -lt 1 ]]; then
    echo "You need to specify which day you're running."
    exit 1
fi
cd day$1
if [[ -n $2 ]]; then
    if [[ $2 -eq 1 ]]; then
        python day$1.py
    elif [[ $2 -eq 2 ]]; then
        python day${1}part2.py
    fi
else
    python day$1.py && python day${1}part2.py
fi